'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  IdiomaEtiquetasDTO.vb
''  Implementation of the Class IdiomaEtiquetasDTO
''  Generated by Enterprise Architect
''  Created on:      16-abr.-2019 21:10:17
''  Original author: seba_
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Public Class IdiomaEtiquetaDTO

    Private _id_etiqueta As Integer
    Private _etiqueta As String
    Private _traduccion As String

    Public Property id_etiqueta() As Integer
        Get
            Return _id_etiqueta
        End Get
        Set(ByVal value As Integer)
            _id_etiqueta = value
        End Set
    End Property

    Public Property etiqueta() As String
        Get
            Return _etiqueta
        End Get
        Set(ByVal Value As String)
            _etiqueta = Value
        End Set
    End Property

    Public Property traduccion() As String
        Get
            Return _traduccion
        End Get
        Set(ByVal Value As String)
            _traduccion = Value
        End Set
    End Property


End Class
