'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  UsuarioDTO.vb
''  Implementation of the Class UsuarioDTO
''  Generated by Enterprise Architect
''  Created on:      06-abr.-2019 19:11:05
''  Original author: seba_
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Public Class UsuarioDTO

    Private _id As Integer
    Private _username As String
    Private _password As String
    Private _nombre As String
    Private _apellido As String
    Private _fechaCreacion As DateTime
    Private _intentos As Integer
    Private _bloqueado As Boolean
    Private _mail As String
    'Private _idioma As IdiomaDTO
    Private _perfil As PerfilCompuesto
    Private _dni As Integer

    Public Property id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            _id = value
        End Set
    End Property

    Public Property apellido() As String
        Get
            Return _apellido
        End Get
        Set(ByVal Value As String)
            _apellido = Value
        End Set
    End Property

    Public Property fechaCreacion() As DateTime
        Get
            Return _fechaCreacion
        End Get
        Set(ByVal Value As DateTime)
            _fechaCreacion = Value
        End Set
    End Property

    Public Property nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property

    Public Property password() As String
        Get
            Return _password
        End Get
        Set(ByVal Value As String)
            _password = Value
        End Set
    End Property

    Public Property username() As String
        Get
            Return _username
        End Get
        Set(ByVal Value As String)
            _username = Value
        End Set
    End Property

    Public Property bloqueado() As Boolean
        Get
            Return _bloqueado
        End Get
        Set(ByVal Value As Boolean)
            _bloqueado = Value
        End Set
    End Property

    Public Property intentos() As Integer
        Get
            Return _intentos
        End Get
        Set(ByVal Value As Integer)
            _intentos = Value
        End Set
    End Property

    Public Property mail() As String
        Get
            Return _mail
        End Get
        Set(ByVal value As String)
            _mail = value
        End Set
    End Property

    Public Property perfil() As PerfilCompuesto
        Get
            Return _perfil
        End Get
        Set(ByVal Value As PerfilCompuesto)
            _perfil = Value
        End Set
    End Property

    'Public Property idioma() As IdiomaDTO
    '    Get
    '        Return _idioma
    '    End Get
    '    Set(ByVal Value As IdiomaDTO)
    '        _idioma = Value
    '    End Set
    'End Property

    Public Property dni As Integer
        Get
            Return _dni
        End Get
        Set(ByVal Value As Integer)
            _dni = Value
        End Set
    End Property

End Class ' UsuarioDTO

