USE [master]
GO

/****** Object:  Database [FBM]    Script Date: 16/05/2019 0:54:52 ******/
CREATE DATABASE [FBM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FBM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\FBM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FBM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\FBM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FBM] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FBM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FBM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FBM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FBM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FBM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FBM] SET ARITHABORT OFF 
GO

ALTER DATABASE [FBM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FBM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FBM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FBM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FBM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FBM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FBM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FBM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FBM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FBM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FBM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FBM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FBM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FBM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FBM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FBM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FBM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FBM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FBM] SET  MULTI_USER 
GO

ALTER DATABASE [FBM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FBM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FBM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FBM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FBM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FBM] SET QUERY_STORE = OFF
GO

USE [FBM]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [FBM] SET  READ_WRITE 
GO

